apiVersion: v1
kind: Service
metadata:
  name: {{ include "syself.fullname" . }}
  labels:
    {{- include "syself.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "syself.selectorLabels" . | nindent 4 }}
